Design
devscast/devs-cast.com pull request #24
Opened 2020-09-08 03:04 UTC by Scott-Tresor

2020-09-08 12:47 UTC, bernard-ng commented on src/Controller/PageController.php
> +        $blogs = $this->blogRepository->findAll();
pourquoi tu recupere tout les articles sur la page d'acceuil ?

2020-09-08 12:47 UTC, bernard-ng commented on src/Controller/PostController.php
> +            'posts' => $this->postRepository->findForSidebar(),
pourquoi cette ligne ?

2020-09-08 13:17 UTC, bernard-ng requested changes
le travail que tu as effectué est imcomplet, il beaucoup des fonctionnalités du site que tu as mis en commentaire, je ne sais pas pourquoi, je prendre en compte ton travail une fois que tu as totalement terminé. malheuresement tu as une deadline, jusqu'a samedi

2020-09-08 13:17 UTC, bernard-ng commented on templates/app/blog/_sidebar.html.twig
> -    </section>
la sidebar doit afficher aussi les categories

2020-09-08 13:17 UTC, bernard-ng commented on templates/app/blog/show.html.twig
> +    {# {% endif %} #}
les metas sont important pour le SEO pourquoi c'est en commentaire ?

2020-09-08 13:17 UTC, bernard-ng commented on templates/app/posts/show.html.twig
> +    {# {% endif %} #}
pour tu mets les metas en commentaire ? c'est important pour le SEO !

2020-09-08 13:17 UTC, bernard-ng commented on templates/app/projects/index.html.twig
> -            <div class="calendar animated fadeIn" style="text-align: center">Chargement de l'activité...</div>
l'activité github doit apparaitre sur le site

2020-09-08 13:17 UTC, bernard-ng commented on templates/app/sections/_blog.html.twig
> -        </div>
pourquoi tu as retirer la pagination du blog ?

2020-09-08 13:17 UTC, bernard-ng commented on templates/app/sections/_bloging.html.twig
> +    </div>
pourquoi il y a une section blog et blogging ? cherche un moyen d'eviter cette duplication

2020-09-08 13:17 UTC, bernard-ng commented on templates/app/sections/_incitation.html.twig
> +</div>
pas besoin d'une section pour cette partie

2020-09-08 13:17 UTC, bernard-ng commented on templates/app/statics/conduct.html.twig
> +        {# {{ include('app/documents/conduct.md.twig') | markdown_to_html }} #}
pourquoi tu met le document en commenatire ? c'est lui qui contient le text a afficher

2020-09-08 13:17 UTC, bernard-ng commented on templates/app/statics/conduct.html.twig
> +            </div>
ceci vient d'ou ?

2020-09-08 13:17 UTC, bernard-ng commented on templates/index.html.twig
> +    {% include 'app/sections/_incitation.html.twig' %}
cette section ne doit pas exister, utilise directement le html

2020-09-08 13:17 UTC, bernard-ng commented on templates/index.html.twig
> +    {% include 'app/sections/_incitation.html.twig' %}
et pour tout ce qui nommage, fait le en anglais !

2020-09-09 21:12 UTC, Scott-Tresor commented on src/Controller/PageController.php
> +        $blogs = $this->blogRepository->findAll();
combien  des articles max dois je recuperer ????

2020-09-09 21:15 UTC, Scott-Tresor commented on templates/index.html.twig
> +    {% include 'app/sections/_incitation.html.twig' %}
d'accord

2020-09-09 21:32 UTC, Scott-Tresor commented on templates/index.html.twig
> +    {% include 'app/sections/_incitation.html.twig' %}
d'accors compris

2020-09-09 21:33 UTC, Scott-Tresor commented on templates/app/statics/conduct.html.twig
> +            </div>
c'est dans le design realiser par  meschac

2020-09-09 21:34 UTC, Scott-Tresor commented on templates/app/statics/conduct.html.twig
> +        {# {{ include('app/documents/conduct.md.twig') | markdown_to_html }} #}
je veux corriger  ici

2020-09-09 21:34 UTC, Scott-Tresor commented on templates/app/sections/_incitation.html.twig
> +</div>
ok

2020-09-09 21:35 UTC, Scott-Tresor commented on templates/app/sections/_bloging.html.twig
> +    </div>
Bloging  c'est  les informations  du blog qui sont afficher sur la page d'acceuil  et blog  c'est pour la section blog

2020-09-09 21:36 UTC, Scott-Tresor commented on templates/app/blog/show.html.twig
> +    {# {% endif %} #}
a revoir

2020-09-09 21:36 UTC, Scott-Tresor commented on templates/app/blog/_sidebar.html.twig
> -    </section>
c'est ce que j'ai fait

2020-09-09 21:41 UTC, Scott-Tresor commented on src/Controller/PostController.php
> +            'posts' => $this->postRepository->findForSidebar(),
we  c'est ici  ou j'avais rencontrer un problème, tout ce que j'ai fait  c'est l'adapter  au nouveau design qui sépare le blog  et le tutoriels dans l'affichage de  l'interface

2020-09-09 21:41 UTC, Scott-Tresor commented on src/Controller/PageController.php
>      /**
donc je dois enlever la section  blog sur la page  d'acceuil

2020-09-09 21:42 UTC, Scott-Tresor commented on .env
> +DATABASE_URL=mysql://root:root@127.0.0.1:3306/devs-cast?
deja fait

2020-09-09 21:47 UTC, bernard-ng requested changes

2020-09-09 21:47 UTC, bernard-ng commented on templates/app/blog/show.html.twig
>  {% endblock %}
cette section est toujours en commentaire

2020-09-09 22:55 UTC, bernard-ng approved these changes

2020-09-09 22:55 UTC, merged